services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kartik
      POSTGRES_DB: cafemanagement  # ✅ Ensures the database is created
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork  # ✅ Using mynetwork
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork  # ✅ Using mynetwork

  cafemansys:
    image: cafe-man-sys
    container_name: cafemansys
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cafemanagement
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: kartik
      SPRING_PROFILES_ACTIVE: docker  # ✅ Fixed indentation
    networks:
      - mynetwork  # ✅ Using mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    external: true  # ✅ Using your created external network
